include Windows in matrix

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -5,7 +5,7 @@ on: [push, pull_request]
 env:
   PY_COLOR: 1
   COLUMNS: 120
-  TESSDATA_PREFIX: /usr/local/share/tessdata
+  LETSGODIGITAL: https://github.com/arturaugusto/display_ocr/raw/master/letsgodigital/letsgodigital.traineddata
 
 jobs:
 
@@ -17,7 +17,7 @@ jobs:
       fail-fast: false
       matrix:
         python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
-        os: [ubuntu]
+        os: [windows, ubuntu]
         architecture: [x64]
 
     steps:
@@ -28,28 +28,40 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
           architecture: ${{ matrix.architecture }}
-      - name: Install tesseract-ocr
+      - name: Install tesseract-ocr (Ubuntu)
+        if: ${{ matrix.os == 'ubuntu' }}
         run: |
           sudo add-apt-repository ppa:alex-p/tesseract-ocr-devel
           sudo apt-get update
           sudo apt-get install tesseract-ocr
-          sudo wget https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata -P $TESSDATA_PREFIX
-          sudo wget https://github.com/arturaugusto/display_ocr/raw/master/letsgodigital/letsgodigital.traineddata -P $TESSDATA_PREFIX
-      - name: Build and install ssocr
+          sudo wget $LETSGODIGITAL -P /usr/share/tesseract-ocr/5/tessdata/
+      - name: Install tesseract-ocr (Windows)
+        if: ${{ matrix.os == 'windows' }}
+        run: |
+          curl https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.2.0.20220712.exe -o tesseract-setup.exe
+          7z x tesseract-setup.exe -otesseract
+          Add-Content $env:GITHUB_PATH .\tesseract
+          curl $env:LETSGODIGITAL -o .\tesseract\tessdata\letsgodigital.traineddata
+      - name: Build and install ssocr (Ubuntu)
+        if: ${{ matrix.os == 'ubuntu' }}
         run: |
           sudo apt-get install libimlib2 libimlib2-dev
           git clone https://github.com/auerswal/ssocr.git
           cd ssocr/
           make
           sudo make install
+      - name: Verify tesseract
+        run: |
+          tesseract --version
+          tesseract --list-langs
+      - name: Verify ssocr (Ubuntu)
+        if: ${{ matrix.os == 'ubuntu' }}
+        # "ssocr --version" has an exit code of 42, so it must be ignored
+        run: ssocr --version || true
       - name: Install Python dependencies and package
         run: |
           python -m pip install --upgrade pip
           python -m pip install --upgrade setuptools wheel
           python -m pip install --upgrade --editable .[tests]
       - name: Run tests
-        run: |
-          tesseract --version
-          tesseract --list-langs
-          ssocr --version || true
-          python -m pytest
+        run: python -m pytest
